[package]
name = "rust_wasm_router"
version = "0.4.3"
authors = ["Luciano Bestia <Luciano.Bestia@gmail.com>"]
edition = "2018"
description = "wasm router for local hash routes"
repository = "https://github.com/LucianoBestia/rust_wasm_router"
readme = "README.md"
license = "MIT"
keywords = ["wasm","router","hash"]
categories = ["wasm","web-programming"]
# publish as a crates.io library. Only this files.
publish = true
include = [
    "Cargo.toml",
    "LICENSE",
    "README.md",
    "src/*",
]

[dependencies]
rust_wasm_websys_utils = "0.4.3"
# rust_wasm_websys_utils = {path = "../rust_wasm_websys_utils"}

unwrap = "1.2.1"
#dodrio =  { git = "https://github.com/fitzgen/dodrio", branch = "master" }
dodrio = {path = "../dodrio"}
wasm-bindgen = { version = "0.2.58", features = ["serde-serialize"] }
#newer version of rand do not have smallring
rand = { version = "0.7.3", features = ["wasm-bindgen","small_rng"] }
js-sys = "0.3"
serde ="1.0.104"
serde_json = "1.0"
# newer futures have unstable .await
wasm-bindgen-futures = "0.4.8"

[dependencies.web-sys]
version = "0.3.33"
features = [
  "console",
  "Document",
  "Element",
  "ErrorEvent",
  "Event",
  "EventListener",
  "EventTarget",
  "History",
  "HtmlAudioElement",
  "HtmlElement",
  "HtmlImageElement",
  "HtmlInputElement",
  "HtmlMediaElement",
  "KeyboardEvent",
  "Location",
  "MouseEvent",
  "Navigator",
  "Node",
  "Request",
  "RequestCache",
  "RequestCredentials",
  "RequestInit",
  "RequestMode",
  "RequestRedirect",
  "Response",
  "Storage",
  "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.3.8"